export enum  Types {
    number = 'NUMBER',
    string = 'STRING',
    boolean = 'BOOLEAN',
    date = 'DATE',
    json = 'JSON',
    number_array = 'NUMBER_ARRAY',
    string_array = 'STRING_ARRAY',
    boolean_array = 'BOOLEAN_ARRAY',
    date_array = 'DATE_ARRAY',
    json_array = 'JSON_ARRAY',
    array_array = 'ARRAY_ARRAY',
    numer_node = 'NUMBER_NODE',
    string_node = 'STRING_NODE',
    boolean_node = 'BOOLEAN_NODE',
    date_node = 'DATE_NODE',
    json_node = 'JSON_NODE',
    number_array_node = 'NUMBER_ARRAY_NODE',
    string_array_node = 'STRING_ARRAY_NODE',
    boolean_array_node = 'BOOLEAN_ARRAY_NODE',
    date_array_node = 'DATE_ARRAY_NODE',
    json_array_node = 'JSON_ARRAY_NODE',
    array_array_node = 'ARRAY_ARRAY_NODE'
}
